fixing pictures partial after introducing inline galleries (https://github.com/fiedl/your_platform/commit/7024d21697e92a40fa84780b3db9a3cf4d974555).
This has caused the error:

  An ActionView::Template::Error occurred in news#index:
  undefined local variable or method `inline' for #<#<Class:0x007fd2b11043f8>:0x007fd2b080a220>

Trello: https://trello.com/c/pdTtVK2v/923-fix-fehler-in-news-index-for-inline